// Shared domain types for the passport planner.

/** A participant museum, as generated by the data pipeline into museums.json. */
export interface Museum {
  id: number
  name: string
  address: string
  region: string
  state: string
  country: string
  lat: number
  lon: number
  url: string | null
  phone: string | null
  email: string | null
  /** Individual-tier memberships that carry passport benefits (may be empty). */
  individualTiers: string[]
  /** Group/family-tier memberships that carry passport benefits (may be empty). */
  groupTiers: string[]
  proofOfResidence: boolean
}

/** Anything with coordinates — the argument shape for distance math. */
export interface LatLon {
  lat: number
  lon: number
}

/** The visitor's chosen residence, from address search or a dropped map pin. */
export interface Home extends LatLon {
  label: string
}

/** Passport eligibility of a single museum given the current home + member. */
export type Status = 'unknown' | 'eligible' | 'excluded' | 'member'

export interface MuseumStatus {
  status: Status
  /** Straight-line miles from home, or null when no home is set. */
  dHome: number | null
  /** Straight-line miles from the member museum, or null when none is picked. */
  dMember: number | null
}

/** Per-museum status keyed by museum id. Every museum is always present. */
export type StatusMap = Map<number, MuseumStatus>

/** A ranked membership candidate and how many faraway museums it unlocks. */
export interface Recommendation {
  museum: Museum
  dHome: number
  unlocked: number
}

/** A normalized geocoder hit, ready to render and to become a Home. */
export interface DescribedPlace {
  primary: string
  secondary: string
  label: string
}

export interface GeoResult extends DescribedPlace, LatLon {}
